# Generated by Django 2.0.13 on 2019-06-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='listing',
            name='tag',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
