# Generated by Django 2.2.3 on 2019-07-19 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing', '0002_remove_listing_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_upvoted', models.ForeignKey(default='Default Business Name', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='listing.Listing')),
                ('voter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
