# Generated by Django 2.0.13 on 2019-06-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20190617_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='name',
        ),
    ]
