# Generated by Django 2.2.3 on 2019-07-30 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_upvotes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingArchive',
        ),
    ]
