# Generated by Django 2.2.3 on 2019-07-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_delete_listingarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='hard_votes_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
