# Generated by Django 2.0.13 on 2019-06-17 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_remove_listing_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='created_by',
        ),
    ]
