# Generated by Django 2.2.3 on 2019-07-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_auto_20190731_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
