# Generated by Django 2.2.3 on 2019-08-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_auto_20190731_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='tag',
        ),
        migrations.AlterField(
            model_name='listing',
            name='can_offer',
            field=models.TextField(default='Use keywords, such as photography, graphic design, carpentry, dog sitting... ', verbose_name='What are all the really awesome things you can offer in return? Enter as single words or a statement'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Pro tip: Square-ish pics work best.. we wont crop your photos to suit a set window, but that does mean rectangles come out looking a bit funny!'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(default='Web Design, Photography, Cake, Puppies.. (we can dream)', max_length=254, verbose_name='Listing Title.. As it sounds.. what are you looking for?'),
        ),
    ]
