# Generated by Django 2.2.2 on 2019-06-26 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing', '0009_auto_20190626_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Listing Title', max_length=254)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('contact', models.EmailField(default='email@email.com', max_length=254)),
                ('tag', models.TextField()),
                ('can_offer', models.TextField(default=1)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
