# Generated by Django 2.2.2 on 2019-06-26 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing', '0010_listingtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Listing Title', max_length=254)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('contact', models.EmailField(default='email@email.com', max_length=254)),
                ('tag', models.TextField()),
                ('can_offer', models.TextField(default=1)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='created_by',
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ListingTest',
        ),
    ]
