# Generated by Django 2.2.2 on 2019-06-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_auto_20190626_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='listing',
            name='can_offer',
            field=models.TextField(default='Please detail the things you can offer in return as single words, eg catering, photography'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact',
            field=models.EmailField(default='The best email for people to contact you at', max_length=254),
        ),
        migrations.AlterField(
            model_name='listing',
            name='content',
            field=models.TextField(verbose_name='What are you looking for? Be as detailed as possible!'),
        ),
    ]
