# Generated by Django 2.2.2 on 2019-07-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_auto_20190626_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='archive',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
