# Generated by Django 2.2.3 on 2019-08-06 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190726_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
