# Generated by Django 2.2.2 on 2019-06-28 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190626_1739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDetail',
        ),
    ]
