# Generated by Django 2.2.2 on 2019-06-28 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('Agriculture, forestry, fishing and hunting', 'Agriculture, forestry, fishing and hunting'), ('Construction', 'Construction'), ('Manufacturing', 'Manufacturing'), ('Transportation equipment manufacturing', 'Transportation equipment manufacturing'), ('Service industries', 'Service industries'), ('Wholesale Trade', 'Wholesale Trade'), ('Retail Trade', 'Retail Trade'), ('Transportation and warehousing', 'Transportation and warehousing'), ('Information and cultural industries', 'Information and cultural industries'), ('Finance and insurance', 'Finance and insurance'), ('Real estate and rental and leasing', 'Real estate and rental and leasing'), ('Professional, scientific, and technical services', 'Professional, scientific, and technical services'), ('Management of companies and enterprises', 'Management of companies and enterprises'), ('Administrative and support, waste management and remediation services', 'Administrative and support, waste management and remediation services'), ('Mining, quarrying, and oil and gas extraction', 'Mining, quarrying, and oil and gas extraction')], default='Industry', max_length=1)),
                ('contact_email', models.EmailField(default='contact email', max_length=254)),
                ('about_us', models.CharField(default="Information about your company - where you're from, what you do!", max_length=254)),
                ('logo', models.ImageField(upload_to='images')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
