# Generated by Django 2.2.3 on 2019-07-19 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, default='Business Name', max_length=254, null=True)),
                ('industry', models.CharField(blank=True, choices=[('AG', 'Agriculture, forestry, fishing and hunting'), ('CN', 'Construction'), ('MG', 'Manufacturing'), ('TR', 'Transportation equipment manufacturing'), ('SI', 'Service industries'), ('WT', 'Wholesale Trade'), ('RT', 'Retail Trade'), ('TW', 'Transportation and warehousing'), ('IC', 'Information and cultural industries'), ('FI', 'Finance and insurance'), ('RE', 'Real estate and rental and leasing'), ('PS', 'Professional, scientific, and technical services'), ('MA', 'Management of companies and enterprises'), ('AD', 'Administrative and support, waste management and remediation services')], default='Please pick an industry', max_length=254, null=True)),
                ('contact_email', models.EmailField(blank=True, default='email@email.com', max_length=254, null=True)),
                ('about_us', models.TextField(blank=True, default="Information about your company - where you're from, what you do!", null=True)),
                ('address', models.TextField(blank=True, default='Business Address', null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('created_by', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='Review Content', max_length=254, null=True)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('company_reviewed', models.ForeignKey(default='Default Business Name', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='company.CompanyDetail')),
                ('created_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='Review Content', max_length=254, null=True)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('company_reviewed', models.ForeignKey(default='Default Business Name', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='company.CompanyDetail')),
                ('created_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
