# Generated by Django 2.2.3 on 2019-07-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetail',
            name='overall_rating',
        ),
    ]
