# Generated by Django 2.2.3 on 2019-07-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewCompany',
        ),
    ]
