# Generated by Django 2.2.3 on 2019-07-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_delete_reviewcompany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetail',
            old_name='address',
            new_name='street_address',
        ),
        migrations.AddField(
            model_name='companydetail',
            name='city',
            field=models.CharField(blank=True, default='Toronto', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='country',
            field=models.CharField(blank=True, default='Canada', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='industry',
            field=models.CharField(blank=True, choices=[('Agriculture, forestry, fishing and hunting', 'AG'), ('Construction', 'CN'), ('Manufacturing', 'MG'), ('Transportation equipment manufacturing', 'TR'), ('Service industries', 'SI'), ('Wholesale Trade', 'WT'), ('Retail Trade', 'RT'), ('Transportation and warehousing', 'TW'), ('Information and cultural industries', 'IC'), ('Finance and insurance', 'FI'), ('Real estate and rental and leasing', 'RE'), ('Professional, scientific, and technical services', 'PS'), ('Management of companies and enterprises', 'MA'), ('Administrative and support, waste management and remediation services', 'AD')], default='Please pick an industry', max_length=254, null=True),
        ),
    ]
