# Generated by Django 2.2.2 on 2019-07-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190709_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='contact_email',
            field=models.EmailField(default='email@email.com', max_length=254),
        ),
    ]
