# Generated by Django 2.2.3 on 2019-07-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190725_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='remote',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
