# Generated by Django 2.2.2 on 2019-07-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20190709_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetail',
            name='logo',
        ),
    ]
