# Generated by Django 2.2.2 on 2019-07-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20190710_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetail',
            old_name='image',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='companydetail',
            name='business_name',
            field=models.CharField(blank=True, default='Business Name', max_length=254, null=True),
        ),
    ]
