# Generated by Django 2.2.2 on 2019-07-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20190710_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='about_us',
            field=models.TextField(blank=True, default="Information about your company - where you're from, what you do!", null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='address',
            field=models.TextField(blank=True, default='Business Address', null=True),
        ),
    ]
