# Generated by Django 2.2.2 on 2019-07-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20190710_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreview',
            name='company_reviewed',
            field=models.CharField(default='Default Business Name', max_length=254, null=True),
        ),
    ]
