# Generated by Django 2.2.2 on 2019-07-16 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20190716_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreview',
            name='company_reviewed',
            field=models.ForeignKey(default='Default Business Name', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='company.CompanyDetail'),
        ),
    ]
