# Generated by Django 2.2.2 on 2019-07-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20190716_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreview',
            name='content',
            field=models.TextField(default='Review Content', max_length=254, null=True),
        ),
    ]
